[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/parser-utils",
    "crates/parser-markdown",
    "crates/parser-asciidoc",
    "crates/parser-rst",
    "crates/parser-verso",
    "crates/parsers",
    "crates/assemble",
    "crates/translate",
    "crates/cli",
    "crates/server",
]
default-members = ["crates/cli"]
