"""Localize the PEP indices generated by the official Sphinx extension."""

from __future__ import annotations

from pathlib import Path
import re
import unicodedata


HEADINGS = {
    "Introduction": "소개",
    "Topics": "주제별 색인",
    "API": "API",
    "Numerical Index": "번호순 색인",
    "Index by Category": "분류별 색인",
    "Process and Meta-PEPs": "프로세스 및 메타 PEP",
    "Other Informational PEPs": "그 밖의 정보 제공 PEP",
    "Provisional PEPs (provisionally accepted; interface may still change)": "잠정 PEP(잠정 승인, 인터페이스 변경 가능)",
    "Accepted PEPs (accepted; may not be implemented yet)": "승인된 PEP(아직 구현되지 않았을 수 있음)",
    "Open PEPs (under consideration)": "검토 중인 PEP",
    "Finished PEPs (done, with a stable interface)": "완료된 PEP(안정된 인터페이스)",
    "Historical Meta-PEPs and Informational PEPs": "역사적 메타 PEP 및 정보 제공 PEP",
    "Deferred PEPs (postponed pending further research or updates)": "유예된 PEP(추가 연구나 갱신 대기)",
    "Rejected, Superseded, and Withdrawn PEPs": "거부·대체·철회된 PEP",
    "Reserved PEP Numbers": "예약된 PEP 번호",
    "PEP Types Key": "PEP 유형 범례",
    "PEP Status Key": "PEP 상태 범례",
    "Authors/Owners": "저자/담당자",
    "Topic Index": "주제별 색인",
    "Governance PEPs": "거버넌스 PEP",
    "Packaging PEPs": "패키징 PEP",
    "Release PEPs": "릴리스 PEP",
    "Typing PEPs": "타이핑 PEP",
}

REPLACEMENTS = {
    "Title: Index of Python Enhancement Proposals (PEPs)": "Title: Python 개선 제안(PEP) 색인",
    """This PEP contains the index of all Python Enhancement Proposals,
known as PEPs.  PEP numbers are :pep:`assigned <1#pep-editors>`
by the PEP editors, and once assigned are never changed.  The
`version control history <https://github.com/python/peps>`_ of
the PEP texts represent their historical record.""": """이 PEP은 Python 개선 제안(PEP) 전체의 색인입니다. PEP 번호는
:pep:`PEP 편집자가 배정 <1#pep-editors>`\\ 하며, 한 번 배정된 번호는 바뀌지
않습니다. PEP 본문의 `버전 관리 이력 <https://github.com/python/peps>`_\\ 이
각 제안의 역사적 기록입니다.""",
    "PEPs for specialist subjects are :doc:`indexed by topic <topic/index>`.": "전문 분야의 PEP은 :doc:`주제별로 분류 <topic/index>`\\ 되어 있습니다.",
    "The `PEPS API </api/peps.json>`__ is a JSON file of metadata about all the published PEPs. :doc:`Read more here <api/index>`.": "`PEP API </api/peps.json>`__\\ 는 공개된 모든 PEP의 메타데이터를 담은 JSON 파일입니다. :doc:`자세히 보기 <api/index>`.",
    "The :doc:`numerical index </numerical>` contains a table of all PEPs, ordered by number.": ":doc:`번호순 색인 </numerical>`\\ 에는 모든 PEP을 번호순으로 정리한 표가 있습니다.",
    "PEPs are indexed by topic on the pages below:": "아래 페이지에서 PEP을 주제별로 찾아볼 수 있습니다:",
    "None.": "없음.",
    ":pep:`More info in PEP 1 <1#pep-types>`.": ":pep:`PEP 1에서 자세히 보기 <1#pep-types>`.",
    ":pep:`More info in PEP 1 <1#pep-review-resolution>`.": ":pep:`PEP 1에서 자세히 보기 <1#pep-review-resolution>`.",
}

TOPIC_INTROS = {
    "Governance": "거버넌스",
    "Packaging": "패키징",
    "Release": "릴리스",
    "Typing": "타이핑",
}


def display_width(text: str) -> int:
    return sum(2 if unicodedata.east_asian_width(character) in {"W", "F"} else 1 for character in text)


def localize_headings(text: str) -> str:
    lines = text.splitlines(keepends=True)
    for index in range(len(lines) - 1):
        heading = lines[index].rstrip("\r\n")
        translated = HEADINGS.get(heading)
        if translated is None:
            continue
        adornment = lines[index + 1].rstrip("\r\n")
        if not adornment or len(set(adornment)) != 1:
            continue
        newline = "\r\n" if lines[index].endswith("\r\n") else "\n"
        lines[index] = translated + newline
        lines[index + 1] = adornment[0] * max(4, display_width(translated)) + newline
    return "".join(lines)


def localize_text(text: str) -> str:
    for source, translation in REPLACEMENTS.items():
        text = text.replace(source, translation)
    for english, korean in TOPIC_INTROS.items():
        text = text.replace(f"`{english} PEPs <", f"`{korean} PEP <")
        text = text.replace(
            f"This is the index of all Python Enhancement Proposals (PEPs) labelled\nunder the '{english}' topic. This is a sub-index of :pep:`0`,\nthe PEP index.",
            f"이 페이지는 '{korean}' 주제로 분류된 모든 Python 개선 제안(PEP)의\n색인입니다. 전체 PEP 색인인 :pep:`0`\\ 의 하위 색인입니다.",
        )
    text = text.replace("     - Title", "     - 제목")
    text = text.replace("     - Authors", "     - 저자")
    text = text.replace("     - RESERVED", "     - 예약됨")
    text = re.sub(r"^Name( +)Email Address$", r"이름\1이메일 주소", text, flags=re.MULTILINE)
    return localize_headings(text)


def localize_generated_indices(app, env, docnames) -> None:
    source_root = Path(app.srcdir)
    paths = [source_root / "pep-0000.rst", source_root / "numerical.rst"]
    paths.extend(sorted((source_root / "topic").glob("*.rst")))
    for path in paths:
        if not path.is_file():
            continue
        source = path.read_text(encoding="utf-8")
        localized = localize_text(source)
        if localized != source:
            path.write_text(localized, encoding="utf-8")


def setup(app):
    # The official extension generates these files at the default priority 500.
    app.connect("env-before-read-docs", localize_generated_indices, priority=600)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
